name: C# Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout Repository

    - uses: actions/setup-dotnet@v3
      name: Set Up .NET
      with:
        dotnet-version: '7.x'

    - run: dotnet restore
      name: Restore Dependencies

    - run: dotnet build --no-restore --configuration Release
      name: Build the Project
